---
title: "Projects"
editor: visual
---

### Project 1 (Predictive Economic Model on Overall GDP) 

-   Jan 2024 - Mar 2024

-   Description: Using the St. Louis economic data, I looked into which of the explanatory variables would affect GDP the most. Knowing this information would be very helpful for economist to see what policies can be enforced to obtain a better GDP. Using R and regression modeling, I looked into which explanatory variables would be most effective.

-   Used R code / Anova Testing / multiple linear modeling, multicollinearity, predictive ability

```{=html}
<!-- -->
```
-   Regression Modeling to investigate the correlation between explanatory variables and GDP

-   Explanatory variables: personal consumption expenditure, median price of household, federal debt, federal expenditure on interest payments

-   Results: Median Price of household and Personal consumption expenditure were the most impactful

### Project 2 (Stuff+)

-   Sept 2023 - Feb 2024

-   Description: Using the UCLA's baseball team's data set, we looked into and calculated the Stuff+ of the pitchers of the UCLA baseball team. Stuff+ quantifies the \"nastiness\" of a given pitch \"based on characteristics like velocity and movement\" to predict its effectiveness. It was graded on a 0-100 scale, with standard deviation 50. We also had to account for various movement statistics provided by Trackman and sort pitches into buckets by type (i.e. fastballs, breaking balls, and offspeed)

-   Used R and Python / sklearn, pandas, numpy, xgboost / data analysis and data manipulation

-   Results: pitches can keep the movement profile on sliders while throwing it at a higher velocity or adding more sweep

### Project 3 (Pritikin Diet)

-   Dec 2021 - Jan 2022

```{=html}
<!-- -->
```
-   Research Topic: Effectiveness of the Pritikin Diet on the physique of Athletes

-   Description: As sports become increasingly competitive, many athletes strive to improve and enhance their performance in their respective sports. As a result, many athletes have turned to dietary meals to possibly improve their overall performance and nutrition. While diets have been used to lose weight or fat, certain diets arguably have been used to enhance sport performance. Nevertheless, there are still many unanswered questions regarding the positive effects of certain diets on athletic performances (Grandjean 1997). Some notable diets for athletes are the raw food diet, gluten-free diet, fast diet, and paleo diet (Rosenbloom 2014). However, the Pritikin diet has not been thoroughly researched about its effects on the overall performance of an athlete. There have been many published studies on the effects of the various different types of diets on sports like football, soccer, and basketball. However, an analysis on the effect of the Pritikin diet on youth competitive swimmers, a muscle enduring sport (Clarke 2013), has not been conducted. This research examines the Pritikin diet and its effects on the performance of high school swimmers.

-   Used research data / dietary understanding / data and experimental analysis

-   Worked with Professor Beirne (MA, PHD and Post Doctorate from NYU and WashU)

-   Result: The Pritikin Diet had a strong correlation with the physique of athletes
